// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPtmbspGoKTR15tgn0Ih9KotnpAYTMeWA',
    appId: '1:458857501425:web:82b136fa3270cf34e3cf50',
    messagingSenderId: '458857501425',
    projectId: 'fir-7cd43',
    authDomain: 'fir-7cd43.firebaseapp.com',
    storageBucket: 'fir-7cd43.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvdPmL9FLML0Jh2Pgtf6R5vIZ_oaEaFEg',
    appId: '1:458857501425:android:2243d6e839af4f47e3cf50',
    messagingSenderId: '458857501425',
    projectId: 'fir-7cd43',
    storageBucket: 'fir-7cd43.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIpR0-S1SE8dhL-0tmItBiAJ1SDtpQpb0',
    appId: '1:458857501425:ios:1e8ed6d8fab31546e3cf50',
    messagingSenderId: '458857501425',
    projectId: 'fir-7cd43',
    storageBucket: 'fir-7cd43.firebasestorage.app',
    iosBundleId: 'com.example.brgyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIpR0-S1SE8dhL-0tmItBiAJ1SDtpQpb0',
    appId: '1:458857501425:ios:1e8ed6d8fab31546e3cf50',
    messagingSenderId: '458857501425',
    projectId: 'fir-7cd43',
    storageBucket: 'fir-7cd43.firebasestorage.app',
    iosBundleId: 'com.example.brgyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPtmbspGoKTR15tgn0Ih9KotnpAYTMeWA',
    appId: '1:458857501425:web:7f53b25f03abcff9e3cf50',
    messagingSenderId: '458857501425',
    projectId: 'fir-7cd43',
    authDomain: 'fir-7cd43.firebaseapp.com',
    storageBucket: 'fir-7cd43.firebasestorage.app',
  );

}